server:
  port: 9001
  tomcate: 
    max-threds: 10
spring:
  application:
    name: production-system
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://127.0.0.1:3306/production2.0?useSSL=false
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: null
      initial-size: 1
      max-active: 20
      min-idle: 1
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      validation-query: SELECT 1 FROM DUAL
      validation-query-timeout: 30000
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
mybatis:
  type-aliases-package: com.mzj.api.entity.authority
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka/
    register-with-euraka: true
    fetch-register: true
  instance: 
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-inseconds: 2

    
    