spring:
  application:
    name: production-eureka
server:
  port: 9100
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8100/eureka/
    register-with-euraka: true
    fetch-register: true